//===----------------------------------------------------------------------===//
//
// This source file is part of the Teco open source project.
//
// Copyright (c) 2022 the Teco project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by TecoServiceGenerator.
// DO NOT EDIT.

extension TCVpcError {
    public struct InvalidSecurityGroupID: TCErrorType {
        enum Code: String {
            case malformed = "InvalidSecurityGroupID.Malformed"
            case notFound = "InvalidSecurityGroupID.NotFound"
        }
        
        private let error: Code
        
        public let context: TCErrorContext?
        
        public var errorCode: String {
            self.error.rawValue
        }
        
        /// Initializer used by ``TCClient`` to match an error of this type.
        ///
        /// You should not use this initializer directly as there are no public initializers for ``TCErrorContext``.
        public init ?(errorCode: String, context: TCErrorContext) {
            guard let error = Code(rawValue: errorCode) else {
                return nil
            }
            self.error = error
            self.context = context
        }
        
        internal init (_ error: Code, context: TCErrorContext? = nil) {
            self.error = error
            self.context = context
        }
        
        /// 无效的安全组,安全组实例ID不合法。
        public static var malformed: InvalidSecurityGroupID {
            InvalidSecurityGroupID(.malformed)
        }
        
        /// 无效的安全组,安全组实例ID不存在。
        public static var notFound: InvalidSecurityGroupID {
            InvalidSecurityGroupID(.notFound)
        }
    }
}

extension TCVpcError.InvalidSecurityGroupID: Equatable {
    public static func == (lhs: TCVpcError.InvalidSecurityGroupID, rhs: TCVpcError.InvalidSecurityGroupID) -> Bool {
        lhs.error == rhs.error
    }
}

extension TCVpcError.InvalidSecurityGroupID: CustomStringConvertible {
    public var description: String {
        return "\(self.error.rawValue): \(message ?? "")"
    }
}

extension TCVpcError.InvalidSecurityGroupID {
    /// - Returns: ``TCVpcError`` that holds the same error and context.
    public func toVpcError() -> TCVpcError {
        guard let code = TCVpcError.Code(rawValue: self.error.rawValue) else {
            fatalError("Unexpected internal conversion error!\nPlease file a bug at https://github.com/teco-project/teco to help address the problem.")
        }
        return TCVpcError(code, context: self.context)
    }
}

extension TCVpcError.InvalidSecurityGroupID {
    /// - Returns: ``TCCommonError`` that holds the same error and context.
    public func toCommonError() -> TCCommonError? {
        if let context = self.context, let error = TCCommonError(errorCode: self.error.rawValue, context: context) {
            return error
        }
        return nil
    }
}
