//===----------------------------------------------------------------------===//
//
// This source file is part of the Teco open source project.
//
// Copyright (c) 2022 the Teco project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Teco project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by TecoServiceGenerator.
// DO NOT EDIT.

extension TCSsaError {
    public struct UnauthorizedOperation: TCErrorType {
        enum Code: String {
            case subAccountUnauthorized = "UnauthorizedOperation.SubAccountUnauthorized"
            case other = "UnauthorizedOperation"
        }
        
        private let error: Code
        
        public let context: TCErrorContext?
        
        public var errorCode: String {
            self.error.rawValue
        }
        
        public init ?(errorCode: String, context: TCErrorContext) {
            guard let error = Code(rawValue: errorCode) else {
                return nil
            }
            self.error = error
            self.context = context
        }
        
        internal init (_ error: Code, context: TCErrorContext? = nil) {
            self.error = error
            self.context = context
        }
        
        /// 子账号没有权限操作。
        public static var subAccountUnauthorized: UnauthorizedOperation {
            UnauthorizedOperation(.subAccountUnauthorized)
        }
        
        /// 未授权操作。
        public static var other: UnauthorizedOperation {
            UnauthorizedOperation(.other)
        }
    }
}

extension TCSsaError.UnauthorizedOperation: Equatable {
    public static func == (lhs: TCSsaError.UnauthorizedOperation, rhs: TCSsaError.UnauthorizedOperation) -> Bool {
        lhs.error == rhs.error
    }
}

extension TCSsaError.UnauthorizedOperation: CustomStringConvertible {
    public var description: String {
        return "\(self.error.rawValue): \(message ?? "")"
    }
}

extension TCSsaError.UnauthorizedOperation {
    public func toSsaError() -> TCSsaError {
        guard let code = TCSsaError.Code(rawValue: self.error.rawValue) else {
            fatalError("Unexpected internal conversion error!\nPlease file a bug at https://github.com/teco-project/teco to help address the problem.")
        }
        return TCSsaError(code, context: self.context)
    }
}