//===----------------------------------------------------------------------===//
//
// This source file is part of the Teco open source project
//
// Copyright (c) 2022-2023 the Teco project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by TecoServiceGenerator.
// DO NOT EDIT.

import Logging
import NIOCore
import TecoCore

extension Tcr {
    /// DeleteImagePersonal请求参数结构体
    public struct DeleteImagePersonalRequest: TCRequest {
        /// 仓库名称
        public let repoName: String

        /// Tag名
        public let tag: String

        public init(repoName: String, tag: String) {
            self.repoName = repoName
            self.tag = tag
        }

        enum CodingKeys: String, CodingKey {
            case repoName = "RepoName"
            case tag = "Tag"
        }
    }

    /// DeleteImagePersonal返回参数结构体
    public struct DeleteImagePersonalResponse: TCResponse {
        /// 唯一请求 ID，每次请求都会返回。定位问题时需要提供该次请求的 RequestId。
        public let requestId: String

        enum CodingKeys: String, CodingKey {
            case requestId = "RequestId"
        }
    }

    /// 删除个人版仓库tag
    ///
    /// 用于在个人版中删除tag
    @inlinable @discardableResult
    public func deleteImagePersonal(_ input: DeleteImagePersonalRequest, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) -> EventLoopFuture<DeleteImagePersonalResponse> {
        self.client.execute(action: "DeleteImagePersonal", region: region, serviceConfig: self.config, input: input, logger: logger, on: eventLoop)
    }

    /// 删除个人版仓库tag
    ///
    /// 用于在个人版中删除tag
    @inlinable @discardableResult
    public func deleteImagePersonal(_ input: DeleteImagePersonalRequest, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) async throws -> DeleteImagePersonalResponse {
        try await self.client.execute(action: "DeleteImagePersonal", region: region, serviceConfig: self.config, input: input, logger: logger, on: eventLoop).get()
    }

    /// 删除个人版仓库tag
    ///
    /// 用于在个人版中删除tag
    @inlinable @discardableResult
    public func deleteImagePersonal(repoName: String, tag: String, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) -> EventLoopFuture<DeleteImagePersonalResponse> {
        self.deleteImagePersonal(.init(repoName: repoName, tag: tag), region: region, logger: logger, on: eventLoop)
    }

    /// 删除个人版仓库tag
    ///
    /// 用于在个人版中删除tag
    @inlinable @discardableResult
    public func deleteImagePersonal(repoName: String, tag: String, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) async throws -> DeleteImagePersonalResponse {
        try await self.deleteImagePersonal(.init(repoName: repoName, tag: tag), region: region, logger: logger, on: eventLoop)
    }
}
