//===----------------------------------------------------------------------===//
//
// This source file is part of the Teco open source project
//
// Copyright (c) 2022-2023 the Teco project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by TecoServiceGenerator.
// DO NOT EDIT.

@_exported import struct Foundation.Date
import TecoDateHelpers

extension Teo {
    /// DescribeDDosAttackTopData请求参数结构体
    public struct DescribeDDosAttackTopDataRequest: TCRequestModel {
        /// 开始时间。
        ///
        /// While the wrapped date value is immutable just like other fields, you can customize the projected
        /// string value (through `$`-prefix) in case the synthesized encoding is incorrect.
        @TCTimestampISO8601Encoding public var startTime: Date

        /// 结束时间。
        ///
        /// While the wrapped date value is immutable just like other fields, you can customize the projected
        /// string value (through `$`-prefix) in case the synthesized encoding is incorrect.
        @TCTimestampISO8601Encoding public var endTime: Date

        /// 统计指标列表，取值有：
        /// <li>ddos_attackFlux_protocol ：攻击总流量协议类型分布排行 ；</li>
        /// <li>ddos_attackPackageNum_protocol ：攻击总包量协议类型分布排行 ；</li>
        /// <li>ddos_attackNum_attackType ：攻击总次数攻击类型分布排行 ；</li>
        /// <li>ddos_attackNum_sregion ：攻击总次数攻击源地区分布排行 ；</li>
        /// <li>ddos_attackFlux_sip ：攻击总流量攻击源ip分布排行 ；</li>
        /// <li>ddos_attackFlux_sregion ：攻击总流量攻击源地区分布排行 。</li>
        public let metricName: String

        /// 查询前多少个，传值为0返回全量。
        public let limit: Int64

        /// 站点id集合，不填默认选择全部站点。
        public let zoneIds: [String]?

        /// ddos策略组id 集合，不填默认选择全部策略id。
        public let policyIds: [Int64]?

        /// 端口号。
        public let port: Int64?

        /// 协议类型，取值有：
        /// <li>tcp ；</li>
        /// <li>udp ；</li>
        /// <li>all 。</li>
        public let protocolType: String?

        /// 攻击类型，取值有：
        /// <li>flood ；</li>
        /// <li>icmpFlood ；</li>
        /// <li>all 。</li>
        public let attackType: String?

        /// 数据归属地区，取值有：
        /// <li>overseas ：全球（除中国大陆地区）数据 ；</li>
        /// <li>mainland ：中国大陆地区数据 。</li>不填默认查询overseas。
        public let area: String?

        public init(startTime: Date, endTime: Date, metricName: String, limit: Int64, zoneIds: [String]? = nil, policyIds: [Int64]? = nil, port: Int64? = nil, protocolType: String? = nil, attackType: String? = nil, area: String? = nil) {
            self._startTime = .init(wrappedValue: startTime)
            self._endTime = .init(wrappedValue: endTime)
            self.metricName = metricName
            self.limit = limit
            self.zoneIds = zoneIds
            self.policyIds = policyIds
            self.port = port
            self.protocolType = protocolType
            self.attackType = attackType
            self.area = area
        }

        enum CodingKeys: String, CodingKey {
            case startTime = "StartTime"
            case endTime = "EndTime"
            case metricName = "MetricName"
            case limit = "Limit"
            case zoneIds = "ZoneIds"
            case policyIds = "PolicyIds"
            case port = "Port"
            case protocolType = "ProtocolType"
            case attackType = "AttackType"
            case area = "Area"
        }
    }

    /// DescribeDDosAttackTopData返回参数结构体
    public struct DescribeDDosAttackTopDataResponse: TCResponseModel {
        /// top数据内容
        public let data: [TopNEntry]

        /// 请求响应状态，取值有：
        /// <li>1 ：失败 ；</li>
        /// <li>0 ：成功 。</li>
        public let status: Int64

        /// 请求响应消息。
        public let msg: String

        /// 唯一请求 ID，每次请求都会返回。定位问题时需要提供该次请求的 RequestId。
        public let requestId: String

        enum CodingKeys: String, CodingKey {
            case data = "Data"
            case status = "Status"
            case msg = "Msg"
            case requestId = "RequestId"
        }
    }

    /// 查询DDos攻击Top数据
    @inlinable
    public func describeDDosAttackTopData(_ input: DescribeDDosAttackTopDataRequest, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) -> EventLoopFuture<DescribeDDosAttackTopDataResponse> {
        self.client.execute(action: "DescribeDDosAttackTopData", region: region, serviceConfig: self.config, input: input, logger: logger, on: eventLoop)
    }

    /// 查询DDos攻击Top数据
    @inlinable
    public func describeDDosAttackTopData(_ input: DescribeDDosAttackTopDataRequest, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) async throws -> DescribeDDosAttackTopDataResponse {
        try await self.client.execute(action: "DescribeDDosAttackTopData", region: region, serviceConfig: self.config, input: input, logger: logger, on: eventLoop).get()
    }

    /// 查询DDos攻击Top数据
    @inlinable
    public func describeDDosAttackTopData(startTime: Date, endTime: Date, metricName: String, limit: Int64, zoneIds: [String]? = nil, policyIds: [Int64]? = nil, port: Int64? = nil, protocolType: String? = nil, attackType: String? = nil, area: String? = nil, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) -> EventLoopFuture<DescribeDDosAttackTopDataResponse> {
        self.describeDDosAttackTopData(.init(startTime: startTime, endTime: endTime, metricName: metricName, limit: limit, zoneIds: zoneIds, policyIds: policyIds, port: port, protocolType: protocolType, attackType: attackType, area: area), region: region, logger: logger, on: eventLoop)
    }

    /// 查询DDos攻击Top数据
    @inlinable
    public func describeDDosAttackTopData(startTime: Date, endTime: Date, metricName: String, limit: Int64, zoneIds: [String]? = nil, policyIds: [Int64]? = nil, port: Int64? = nil, protocolType: String? = nil, attackType: String? = nil, area: String? = nil, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) async throws -> DescribeDDosAttackTopDataResponse {
        try await self.describeDDosAttackTopData(.init(startTime: startTime, endTime: endTime, metricName: metricName, limit: limit, zoneIds: zoneIds, policyIds: policyIds, port: port, protocolType: protocolType, attackType: attackType, area: area), region: region, logger: logger, on: eventLoop)
    }
}
