//===----------------------------------------------------------------------===//
//
// This source file is part of the Teco open source project.
//
// Copyright (c) 2022 the Teco project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by TecoServiceGenerator.
// DO NOT EDIT.

extension TCMsError {
    public struct ResourceUnavailable: TCErrorType {
        enum Code: String {
            case notBind = "ResourceUnavailable.NotBind"
            case notFound = "ResourceUnavailable.NotFound"
            case other = "ResourceUnavailable"
        }
        
        private let error: Code
        
        public let context: TCErrorContext?
        
        public var errorCode: String {
            self.error.rawValue
        }
        
        /// Initializer used by ``TCClient`` to match an error of this type.
        ///
        /// You should not use this initializer directly as there are no public initializers for ``TCErrorContext``.
        public init ?(errorCode: String, context: TCErrorContext) {
            guard let error = Code(rawValue: errorCode) else {
                return nil
            }
            self.error = error
            self.context = context
        }
        
        internal init (_ error: Code, context: TCErrorContext? = nil) {
            self.error = error
            self.context = context
        }
        
        /// 资源未绑定应用包名。
        public static var notBind: ResourceUnavailable {
            ResourceUnavailable(.notBind)
        }
        
        /// 找不到该资源。
        public static var notFound: ResourceUnavailable {
            ResourceUnavailable(.notFound)
        }
        
        /// 资源不可用。
        public static var other: ResourceUnavailable {
            ResourceUnavailable(.other)
        }
    }
}

extension TCMsError.ResourceUnavailable: Equatable {
    public static func == (lhs: TCMsError.ResourceUnavailable, rhs: TCMsError.ResourceUnavailable) -> Bool {
        lhs.error == rhs.error
    }
}

extension TCMsError.ResourceUnavailable: CustomStringConvertible {
    public var description: String {
        return "\(self.error.rawValue): \(message ?? "")"
    }
}

extension TCMsError.ResourceUnavailable {
    /// - Returns: ``TCMsError`` that holds the same error and context.
    public func toMsError() -> TCMsError {
        guard let code = TCMsError.Code(rawValue: self.error.rawValue) else {
            fatalError("Unexpected internal conversion error!\nPlease file a bug at https://github.com/teco-project/teco to help address the problem.")
        }
        return TCMsError(code, context: self.context)
    }
}

extension TCMsError.ResourceUnavailable {
    /// - Returns: ``TCCommonError`` that holds the same error and context.
    public func toCommonError() -> TCCommonError? {
        if let context = self.context, let error = TCCommonError(errorCode: self.error.rawValue, context: context) {
            return error
        }
        return nil
    }
}
