name: Build
on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-20.04
        swift:
          - '5.5'
          - '5.6'
          - '5.7'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up private repository access
        env:
          TECO_CI_TOKEN: ${{ secrets.TECO_CI_TOKEN }}
        run: git config --global url."https://x-access-token:${TECO_CI_TOKEN}@github.com/${GITHUB_REPOSITORY_OWNER}/".insteadOf "https://github.com/${GITHUB_REPOSITORY_OWNER}/"
      - name: Build
        run: swift build
