//===----------------------------------------------------------------------===//
//
// This source file is part of the Teco open source project.
//
// Copyright (c) 2022 the Teco project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by TecoServiceGenerator.
// DO NOT EDIT.

extension Tcss {
    /// CreateProcessEventsExportJob请求参数结构体
    public struct CreateProcessEventsExportJobRequest: TCRequestModel {
        /// 需要返回的数量，最大值为10000
        public let limit: UInt64?

        /// 偏移量，默认为0。
        public let offset: UInt64?

        /// 过滤参数,Status：EVENT_UNDEAL:未处理，EVENT_DEALED:已处理，EVENT_INGNORE:忽略
        public let filters: [AssetFilters]?

        /// 升序降序,asc desc
        public let order: String?

        /// 排序字段：latest_found_time
        public let by: String?

        /// 导出字段
        public let exportField: [String]?

        public init(limit: UInt64? = nil, offset: UInt64? = nil, filters: [AssetFilters]? = nil, order: String? = nil, by: String? = nil, exportField: [String]? = nil) {
            self.limit = limit
            self.offset = offset
            self.filters = filters
            self.order = order
            self.by = by
            self.exportField = exportField
        }

        enum CodingKeys: String, CodingKey {
            case limit = "Limit"
            case offset = "Offset"
            case filters = "Filters"
            case order = "Order"
            case by = "By"
            case exportField = "ExportField"
        }
    }

    /// CreateProcessEventsExportJob返回参数结构体
    public struct CreateProcessEventsExportJobResponse: TCResponseModel {
        /// 导出任务ID，前端拿着任务ID查询任务进度
        public let jobId: String

        /// 唯一请求 ID，每次请求都会返回。定位问题时需要提供该次请求的 RequestId。
        public let requestId: String

        enum CodingKeys: String, CodingKey {
            case jobId = "JobId"
            case requestId = "RequestId"
        }
    }

    /// 创建异常进程事件导出异步任务
    @inlinable
    public func createProcessEventsExportJob(_ input: CreateProcessEventsExportJobRequest, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) -> EventLoopFuture<CreateProcessEventsExportJobResponse> {
        self.client.execute(action: "CreateProcessEventsExportJob", serviceConfig: self.config, input: input, logger: logger, on: eventLoop)
    }

    /// 创建异常进程事件导出异步任务
    @inlinable
    public func createProcessEventsExportJob(_ input: CreateProcessEventsExportJobRequest, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) async throws -> CreateProcessEventsExportJobResponse {
        try await self.client.execute(action: "CreateProcessEventsExportJob", serviceConfig: self.config, input: input, logger: logger, on: eventLoop).get()
    }

    /// 创建异常进程事件导出异步任务
    @inlinable
    public func createProcessEventsExportJob(limit: UInt64? = nil, offset: UInt64? = nil, filters: [AssetFilters]? = nil, order: String? = nil, by: String? = nil, exportField: [String]? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) -> EventLoopFuture<CreateProcessEventsExportJobResponse> {
        self.createProcessEventsExportJob(CreateProcessEventsExportJobRequest(limit: limit, offset: offset, filters: filters, order: order, by: by, exportField: exportField), logger: logger, on: eventLoop)
    }

    /// 创建异常进程事件导出异步任务
    @inlinable
    public func createProcessEventsExportJob(limit: UInt64? = nil, offset: UInt64? = nil, filters: [AssetFilters]? = nil, order: String? = nil, by: String? = nil, exportField: [String]? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) async throws -> CreateProcessEventsExportJobResponse {
        try await self.createProcessEventsExportJob(CreateProcessEventsExportJobRequest(limit: limit, offset: offset, filters: filters, order: order, by: by, exportField: exportField), logger: logger, on: eventLoop)
    }
}
