//===----------------------------------------------------------------------===//
//
// This source file is part of the Teco open source project
//
// Copyright (c) 2022-2023 the Teco project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by TecoServiceGenerator.
// DO NOT EDIT.

import TecoCore

extension Tcss {
    /// CreateNetworkFirewallClusterRefresh请求参数结构体
    public struct CreateNetworkFirewallClusterRefreshRequest: TCRequestModel {
        public init() {
        }
    }

    /// CreateNetworkFirewallClusterRefresh返回参数结构体
    public struct CreateNetworkFirewallClusterRefreshResponse: TCResponseModel {
        /// 返回创建的集群检查任务的ID，为0表示创建失败。
        public let taskId: UInt64

        /// 创建检查任务的结果，"Succ"为成功，"Failed"为失败
        public let result: String

        /// 唯一请求 ID，每次请求都会返回。定位问题时需要提供该次请求的 RequestId。
        public let requestId: String

        enum CodingKeys: String, CodingKey {
            case taskId = "TaskId"
            case result = "Result"
            case requestId = "RequestId"
        }
    }

    /// 容器网络集群下发刷新任务
    @inlinable
    public func createNetworkFirewallClusterRefresh(_ input: CreateNetworkFirewallClusterRefreshRequest, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) -> EventLoopFuture<CreateNetworkFirewallClusterRefreshResponse> {
        self.client.execute(action: "CreateNetworkFirewallClusterRefresh", region: region, serviceConfig: self.config, input: input, logger: logger, on: eventLoop)
    }

    /// 容器网络集群下发刷新任务
    @inlinable
    public func createNetworkFirewallClusterRefresh(_ input: CreateNetworkFirewallClusterRefreshRequest, region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) async throws -> CreateNetworkFirewallClusterRefreshResponse {
        try await self.client.execute(action: "CreateNetworkFirewallClusterRefresh", region: region, serviceConfig: self.config, input: input, logger: logger, on: eventLoop).get()
    }

    /// 容器网络集群下发刷新任务
    @inlinable
    public func createNetworkFirewallClusterRefresh(region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) -> EventLoopFuture<CreateNetworkFirewallClusterRefreshResponse> {
        self.createNetworkFirewallClusterRefresh(.init(), region: region, logger: logger, on: eventLoop)
    }

    /// 容器网络集群下发刷新任务
    @inlinable
    public func createNetworkFirewallClusterRefresh(region: TCRegion? = nil, logger: Logger = TCClient.loggingDisabled, on eventLoop: EventLoop? = nil) async throws -> CreateNetworkFirewallClusterRefreshResponse {
        try await self.createNetworkFirewallClusterRefresh(.init(), region: region, logger: logger, on: eventLoop)
    }
}
